[project]
name = "zayavlenie-v-dormitory-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.3",
    "fastapi>=0.133.0",
    "pydantic-settings>=2.13.1",
    "uvicorn>=0.41.0",
]
